language: node_js

node_js:
  - "6"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
  - node_modules/.bin/newman run FirstCollection/FirstCollection.postman_collection.json -e FirstCollection/Test.env.postman_environment.json 
  - node_modules/.bin/newman run SecondCollection/SecondCollection.postman_collection.json -d SecondCollection/test.json -e SecondCollection/Filter.env.postman_environment.json
