language: node_js

node_js:
  - "6"

before_install:
  - npm install -g newman

script:
  - npm newman run FirstCollection\FirstCollection.postman_collection.json -e FirstCollection\Test.env.postman_environment.json 